/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoctorsArmRouteImport } from './routes/doctors-arm'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GiveRouteImport } from './routes/give'
import { Route as GlobalNetworkRouteImport } from './routes/global-network'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as MediaResourcesRouteImport } from './routes/media-resources'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as StudentsArmRouteImport } from './routes/students-arm'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutHistoryRouteImport } from './routes/about/history'
import { Route as ChaptersIndexRouteImport } from './routes/chapters/index'
import { Route as ChaptersSlugRouteImport } from './routes/chapters/$slug'
import { Route as GlobalNetworkSlugRouteImport } from './routes/global-network/$slug'
import { Route as MinistriesExcelRouteImport } from './routes/ministries/excel'
import { Route as MinistriesIfehlRouteImport } from './routes/ministries/ifehl'
import { Route as MinistriesImmRouteImport } from './routes/ministries/imm'
import { Route as MinistriesSalineTrainingRouteImport } from './routes/ministries/saline-training'
import { Route as MinistriesTheLadyDoctorRouteImport } from './routes/ministries/the-lady-doctor'
import { Route as MinistriesWholenessMissionsRouteImport } from './routes/ministries/wholeness-missions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsArmRoute = DoctorsArmRouteImport.update({
  id: '/doctors-arm',
  path: '/doctors-arm',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalNetworkRoute = GlobalNetworkRouteImport.update({
  id: '/global-network',
  path: '/global-network',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaResourcesRoute = MediaResourcesRouteImport.update({
  id: '/media-resources',
  path: '/media-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsArmRoute = StudentsArmRouteImport.update({
  id: '/students-arm',
  path: '/students-arm',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalNetworkSlugRoute = GlobalNetworkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GlobalNetworkRoute,
} as any)
const MinistriesExcelRoute = MinistriesExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesIfehlRoute = MinistriesIfehlRouteImport.update({
  id: '/ifehl',
  path: '/ifehl',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesImmRoute = MinistriesImmRouteImport.update({
  id: '/imm',
  path: '/imm',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesSalineTrainingRoute =
  MinistriesSalineTrainingRouteImport.update({
    id: '/saline-training',
    path: '/saline-training',
    getParentRoute: () => MinistriesRoute,
  } as any)
const MinistriesTheLadyDoctorRoute = MinistriesTheLadyDoctorRouteImport.update({
  id: '/the-lady-doctor',
  path: '/the-lady-doctor',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesWholenessMissionsRoute =
  MinistriesWholenessMissionsRouteImport.update({
    id: '/wholeness-missions',
    path: '/wholeness-missions',
    getParentRoute: () => MinistriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/doctors-arm': typeof DoctorsArmRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/global-network': typeof GlobalNetworkRouteWithChildren
  '/impact': typeof ImpactRoute
  '/media-resources': typeof MediaResourcesRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/students-arm': typeof StudentsArmRoute
  '/studio': typeof StudioRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/about/history': typeof AboutHistoryRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/global-network/$slug': typeof GlobalNetworkSlugRoute
  '/ministries/excel': typeof MinistriesExcelRoute
  '/ministries/ifehl': typeof MinistriesIfehlRoute
  '/ministries/imm': typeof MinistriesImmRoute
  '/ministries/saline-training': typeof MinistriesSalineTrainingRoute
  '/ministries/the-lady-doctor': typeof MinistriesTheLadyDoctorRoute
  '/ministries/wholeness-missions': typeof MinistriesWholenessMissionsRoute
  '/about/': typeof AboutIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/doctors-arm': typeof DoctorsArmRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/global-network': typeof GlobalNetworkRouteWithChildren
  '/impact': typeof ImpactRoute
  '/media-resources': typeof MediaResourcesRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/students-arm': typeof StudentsArmRoute
  '/studio': typeof StudioRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/about/history': typeof AboutHistoryRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/global-network/$slug': typeof GlobalNetworkSlugRoute
  '/ministries/excel': typeof MinistriesExcelRoute
  '/ministries/ifehl': typeof MinistriesIfehlRoute
  '/ministries/imm': typeof MinistriesImmRoute
  '/ministries/saline-training': typeof MinistriesSalineTrainingRoute
  '/ministries/the-lady-doctor': typeof MinistriesTheLadyDoctorRoute
  '/ministries/wholeness-missions': typeof MinistriesWholenessMissionsRoute
  '/about': typeof AboutIndexRoute
  '/chapters': typeof ChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/doctors-arm': typeof DoctorsArmRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/global-network': typeof GlobalNetworkRouteWithChildren
  '/impact': typeof ImpactRoute
  '/media-resources': typeof MediaResourcesRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/students-arm': typeof StudentsArmRoute
  '/studio': typeof StudioRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/about/history': typeof AboutHistoryRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/global-network/$slug': typeof GlobalNetworkSlugRoute
  '/ministries/excel': typeof MinistriesExcelRoute
  '/ministries/ifehl': typeof MinistriesIfehlRoute
  '/ministries/imm': typeof MinistriesImmRoute
  '/ministries/saline-training': typeof MinistriesSalineTrainingRoute
  '/ministries/the-lady-doctor': typeof MinistriesTheLadyDoctorRoute
  '/ministries/wholeness-missions': typeof MinistriesWholenessMissionsRoute
  '/about/': typeof AboutIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/doctors-arm'
    | '/events'
    | '/give'
    | '/global-network'
    | '/impact'
    | '/media-resources'
    | '/membership'
    | '/ministries'
    | '/publications'
    | '/students-arm'
    | '/studio'
    | '/what-we-do'
    | '/about/history'
    | '/chapters/$slug'
    | '/global-network/$slug'
    | '/ministries/excel'
    | '/ministries/ifehl'
    | '/ministries/imm'
    | '/ministries/saline-training'
    | '/ministries/the-lady-doctor'
    | '/ministries/wholeness-missions'
    | '/about/'
    | '/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/doctors-arm'
    | '/events'
    | '/give'
    | '/global-network'
    | '/impact'
    | '/media-resources'
    | '/membership'
    | '/ministries'
    | '/publications'
    | '/students-arm'
    | '/studio'
    | '/what-we-do'
    | '/about/history'
    | '/chapters/$slug'
    | '/global-network/$slug'
    | '/ministries/excel'
    | '/ministries/ifehl'
    | '/ministries/imm'
    | '/ministries/saline-training'
    | '/ministries/the-lady-doctor'
    | '/ministries/wholeness-missions'
    | '/about'
    | '/chapters'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/doctors-arm'
    | '/events'
    | '/give'
    | '/global-network'
    | '/impact'
    | '/media-resources'
    | '/membership'
    | '/ministries'
    | '/publications'
    | '/students-arm'
    | '/studio'
    | '/what-we-do'
    | '/about/history'
    | '/chapters/$slug'
    | '/global-network/$slug'
    | '/ministries/excel'
    | '/ministries/ifehl'
    | '/ministries/imm'
    | '/ministries/saline-training'
    | '/ministries/the-lady-doctor'
    | '/ministries/wholeness-missions'
    | '/about/'
    | '/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DoctorsArmRoute: typeof DoctorsArmRoute
  EventsRoute: typeof EventsRoute
  GiveRoute: typeof GiveRoute
  GlobalNetworkRoute: typeof GlobalNetworkRouteWithChildren
  ImpactRoute: typeof ImpactRoute
  MediaResourcesRoute: typeof MediaResourcesRoute
  MembershipRoute: typeof MembershipRoute
  MinistriesRoute: typeof MinistriesRouteWithChildren
  PublicationsRoute: typeof PublicationsRoute
  StudentsArmRoute: typeof StudentsArmRoute
  StudioRoute: typeof StudioRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors-arm': {
      id: '/doctors-arm'
      path: '/doctors-arm'
      fullPath: '/doctors-arm'
      preLoaderRoute: typeof DoctorsArmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-network': {
      id: '/global-network'
      path: '/global-network'
      fullPath: '/global-network'
      preLoaderRoute: typeof GlobalNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-resources': {
      id: '/media-resources'
      path: '/media-resources'
      fullPath: '/media-resources'
      preLoaderRoute: typeof MediaResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students-arm': {
      id: '/students-arm'
      path: '/students-arm'
      fullPath: '/students-arm'
      preLoaderRoute: typeof StudentsArmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-network/$slug': {
      id: '/global-network/$slug'
      path: '/$slug'
      fullPath: '/global-network/$slug'
      preLoaderRoute: typeof GlobalNetworkSlugRouteImport
      parentRoute: typeof GlobalNetworkRoute
    }
    '/ministries/excel': {
      id: '/ministries/excel'
      path: '/excel'
      fullPath: '/ministries/excel'
      preLoaderRoute: typeof MinistriesExcelRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/ifehl': {
      id: '/ministries/ifehl'
      path: '/ifehl'
      fullPath: '/ministries/ifehl'
      preLoaderRoute: typeof MinistriesIfehlRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/imm': {
      id: '/ministries/imm'
      path: '/imm'
      fullPath: '/ministries/imm'
      preLoaderRoute: typeof MinistriesImmRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/saline-training': {
      id: '/ministries/saline-training'
      path: '/saline-training'
      fullPath: '/ministries/saline-training'
      preLoaderRoute: typeof MinistriesSalineTrainingRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/the-lady-doctor': {
      id: '/ministries/the-lady-doctor'
      path: '/the-lady-doctor'
      fullPath: '/ministries/the-lady-doctor'
      preLoaderRoute: typeof MinistriesTheLadyDoctorRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/wholeness-missions': {
      id: '/ministries/wholeness-missions'
      path: '/wholeness-missions'
      fullPath: '/ministries/wholeness-missions'
      preLoaderRoute: typeof MinistriesWholenessMissionsRouteImport
      parentRoute: typeof MinistriesRoute
    }
  }
}

interface GlobalNetworkRouteChildren {
  GlobalNetworkSlugRoute: typeof GlobalNetworkSlugRoute
}

const GlobalNetworkRouteChildren: GlobalNetworkRouteChildren = {
  GlobalNetworkSlugRoute: GlobalNetworkSlugRoute,
}

const GlobalNetworkRouteWithChildren = GlobalNetworkRoute._addFileChildren(
  GlobalNetworkRouteChildren,
)

interface MinistriesRouteChildren {
  MinistriesExcelRoute: typeof MinistriesExcelRoute
  MinistriesIfehlRoute: typeof MinistriesIfehlRoute
  MinistriesImmRoute: typeof MinistriesImmRoute
  MinistriesSalineTrainingRoute: typeof MinistriesSalineTrainingRoute
  MinistriesTheLadyDoctorRoute: typeof MinistriesTheLadyDoctorRoute
  MinistriesWholenessMissionsRoute: typeof MinistriesWholenessMissionsRoute
}

const MinistriesRouteChildren: MinistriesRouteChildren = {
  MinistriesExcelRoute: MinistriesExcelRoute,
  MinistriesIfehlRoute: MinistriesIfehlRoute,
  MinistriesImmRoute: MinistriesImmRoute,
  MinistriesSalineTrainingRoute: MinistriesSalineTrainingRoute,
  MinistriesTheLadyDoctorRoute: MinistriesTheLadyDoctorRoute,
  MinistriesWholenessMissionsRoute: MinistriesWholenessMissionsRoute,
}

const MinistriesRouteWithChildren = MinistriesRoute._addFileChildren(
  MinistriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DoctorsArmRoute: DoctorsArmRoute,
  EventsRoute: EventsRoute,
  GiveRoute: GiveRoute,
  GlobalNetworkRoute: GlobalNetworkRouteWithChildren,
  ImpactRoute: ImpactRoute,
  MediaResourcesRoute: MediaResourcesRoute,
  MembershipRoute: MembershipRoute,
  MinistriesRoute: MinistriesRouteWithChildren,
  PublicationsRoute: PublicationsRoute,
  StudentsArmRoute: StudentsArmRoute,
  StudioRoute: StudioRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
