/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoctorsArmRouteImport } from './routes/doctors-arm'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GiveRouteImport } from './routes/give'
import { Route as GlobalNetworkRouteImport } from './routes/global-network'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as MediaResourcesRouteImport } from './routes/media-resources'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as StudentsArmRouteImport } from './routes/students-arm'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutHistoryRouteImport } from './routes/about/history'
import { Route as AboutLeadershipRouteImport } from './routes/about/leadership'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ChaptersIndexRouteImport } from './routes/chapters/index'
import { Route as ChaptersSlugRouteImport } from './routes/chapters/$slug'
import { Route as GlobalNetworkSlugRouteImport } from './routes/global-network/$slug'
import { Route as MinistriesExcelRouteImport } from './routes/ministries/excel'
import { Route as MinistriesIfehlRouteImport } from './routes/ministries/ifehl'
import { Route as MinistriesImmRouteImport } from './routes/ministries/imm'
import { Route as MinistriesSalineTrainingRouteImport } from './routes/ministries/saline-training'
import { Route as MinistriesTheLadyDoctorRouteImport } from './routes/ministries/the-lady-doctor'
import { Route as MinistriesWholenessMissionsRouteImport } from './routes/ministries/wholeness-missions'
import { Route as ZonesSlugRouteImport } from './routes/zones/$slug'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutAnnouncementsRouteImport } from './routes/admin/_layout/announcements'
import { Route as AdminLayoutAuditRouteImport } from './routes/admin/_layout/audit'
import { Route as AdminLayoutChaptersRouteImport } from './routes/admin/_layout/chapters'
import { Route as AdminLayoutEventsRouteImport } from './routes/admin/_layout/events'
import { Route as AdminLayoutMediaRouteImport } from './routes/admin/_layout/media'
import { Route as AdminLayoutNewsRouteImport } from './routes/admin/_layout/news'
import { Route as AdminLayoutOutreachesRouteImport } from './routes/admin/_layout/outreaches'
import { Route as AdminLayoutPagesRouteImport } from './routes/admin/_layout/pages'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsArmRoute = DoctorsArmRouteImport.update({
  id: '/doctors-arm',
  path: '/doctors-arm',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalNetworkRoute = GlobalNetworkRouteImport.update({
  id: '/global-network',
  path: '/global-network',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaResourcesRoute = MediaResourcesRouteImport.update({
  id: '/media-resources',
  path: '/media-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsArmRoute = StudentsArmRouteImport.update({
  id: '/students-arm',
  path: '/students-arm',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/about/leadership',
  path: '/about/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalNetworkSlugRoute = GlobalNetworkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GlobalNetworkRoute,
} as any)
const MinistriesExcelRoute = MinistriesExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesIfehlRoute = MinistriesIfehlRouteImport.update({
  id: '/ifehl',
  path: '/ifehl',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesImmRoute = MinistriesImmRouteImport.update({
  id: '/imm',
  path: '/imm',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesSalineTrainingRoute =
  MinistriesSalineTrainingRouteImport.update({
    id: '/saline-training',
    path: '/saline-training',
    getParentRoute: () => MinistriesRoute,
  } as any)
const MinistriesTheLadyDoctorRoute = MinistriesTheLadyDoctorRouteImport.update({
  id: '/the-lady-doctor',
  path: '/the-lady-doctor',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesWholenessMissionsRoute =
  MinistriesWholenessMissionsRouteImport.update({
    id: '/wholeness-missions',
    path: '/wholeness-missions',
    getParentRoute: () => MinistriesRoute,
  } as any)
const ZonesSlugRoute = ZonesSlugRouteImport.update({
  id: '/zones/$slug',
  path: '/zones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAnnouncementsRoute =
  AdminLayoutAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAuditRoute = AdminLayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutChaptersRoute = AdminLayoutChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEventsRoute = AdminLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMediaRoute = AdminLayoutMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutNewsRoute = AdminLayoutNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOutreachesRoute = AdminLayoutOutreachesRouteImport.update({
  id: '/outreaches',
  path: '/outreaches',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutPagesRoute = AdminLayoutPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/doctors-arm': typeof DoctorsArmRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/global-network': typeof GlobalNetworkRouteWithChildren
  '/impact': typeof ImpactRoute
  '/media-resources': typeof MediaResourcesRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/students-arm': typeof StudentsArmRoute
  '/studio': typeof StudioRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/global-network/$slug': typeof GlobalNetworkSlugRoute
  '/ministries/excel': typeof MinistriesExcelRoute
  '/ministries/ifehl': typeof MinistriesIfehlRoute
  '/ministries/imm': typeof MinistriesImmRoute
  '/ministries/saline-training': typeof MinistriesSalineTrainingRoute
  '/ministries/the-lady-doctor': typeof MinistriesTheLadyDoctorRoute
  '/ministries/wholeness-missions': typeof MinistriesWholenessMissionsRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/about/': typeof AboutIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/audit': typeof AdminLayoutAuditRoute
  '/admin/chapters': typeof AdminLayoutChaptersRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/media': typeof AdminLayoutMediaRoute
  '/admin/news': typeof AdminLayoutNewsRoute
  '/admin/outreaches': typeof AdminLayoutOutreachesRoute
  '/admin/pages': typeof AdminLayoutPagesRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/doctors-arm': typeof DoctorsArmRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/global-network': typeof GlobalNetworkRouteWithChildren
  '/impact': typeof ImpactRoute
  '/media-resources': typeof MediaResourcesRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/students-arm': typeof StudentsArmRoute
  '/studio': typeof StudioRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/admin/login': typeof AdminLoginRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/global-network/$slug': typeof GlobalNetworkSlugRoute
  '/ministries/excel': typeof MinistriesExcelRoute
  '/ministries/ifehl': typeof MinistriesIfehlRoute
  '/ministries/imm': typeof MinistriesImmRoute
  '/ministries/saline-training': typeof MinistriesSalineTrainingRoute
  '/ministries/the-lady-doctor': typeof MinistriesTheLadyDoctorRoute
  '/ministries/wholeness-missions': typeof MinistriesWholenessMissionsRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/about': typeof AboutIndexRoute
  '/chapters': typeof ChaptersIndexRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/audit': typeof AdminLayoutAuditRoute
  '/admin/chapters': typeof AdminLayoutChaptersRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/media': typeof AdminLayoutMediaRoute
  '/admin/news': typeof AdminLayoutNewsRoute
  '/admin/outreaches': typeof AdminLayoutOutreachesRoute
  '/admin/pages': typeof AdminLayoutPagesRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/doctors-arm': typeof DoctorsArmRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/global-network': typeof GlobalNetworkRouteWithChildren
  '/impact': typeof ImpactRoute
  '/media-resources': typeof MediaResourcesRoute
  '/membership': typeof MembershipRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/students-arm': typeof StudentsArmRoute
  '/studio': typeof StudioRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/global-network/$slug': typeof GlobalNetworkSlugRoute
  '/ministries/excel': typeof MinistriesExcelRoute
  '/ministries/ifehl': typeof MinistriesIfehlRoute
  '/ministries/imm': typeof MinistriesImmRoute
  '/ministries/saline-training': typeof MinistriesSalineTrainingRoute
  '/ministries/the-lady-doctor': typeof MinistriesTheLadyDoctorRoute
  '/ministries/wholeness-missions': typeof MinistriesWholenessMissionsRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/about/': typeof AboutIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/admin/_layout/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/_layout/audit': typeof AdminLayoutAuditRoute
  '/admin/_layout/chapters': typeof AdminLayoutChaptersRoute
  '/admin/_layout/events': typeof AdminLayoutEventsRoute
  '/admin/_layout/media': typeof AdminLayoutMediaRoute
  '/admin/_layout/news': typeof AdminLayoutNewsRoute
  '/admin/_layout/outreaches': typeof AdminLayoutOutreachesRoute
  '/admin/_layout/pages': typeof AdminLayoutPagesRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/doctors-arm'
    | '/events'
    | '/give'
    | '/global-network'
    | '/impact'
    | '/media-resources'
    | '/membership'
    | '/ministries'
    | '/publications'
    | '/students-arm'
    | '/studio'
    | '/what-we-do'
    | '/about/history'
    | '/about/leadership'
    | '/admin'
    | '/admin/login'
    | '/chapters/$slug'
    | '/global-network/$slug'
    | '/ministries/excel'
    | '/ministries/ifehl'
    | '/ministries/imm'
    | '/ministries/saline-training'
    | '/ministries/the-lady-doctor'
    | '/ministries/wholeness-missions'
    | '/zones/$slug'
    | '/about/'
    | '/chapters/'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/chapters'
    | '/admin/events'
    | '/admin/media'
    | '/admin/news'
    | '/admin/outreaches'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/doctors-arm'
    | '/events'
    | '/give'
    | '/global-network'
    | '/impact'
    | '/media-resources'
    | '/membership'
    | '/ministries'
    | '/publications'
    | '/students-arm'
    | '/studio'
    | '/what-we-do'
    | '/about/history'
    | '/about/leadership'
    | '/admin/login'
    | '/chapters/$slug'
    | '/global-network/$slug'
    | '/ministries/excel'
    | '/ministries/ifehl'
    | '/ministries/imm'
    | '/ministries/saline-training'
    | '/ministries/the-lady-doctor'
    | '/ministries/wholeness-missions'
    | '/zones/$slug'
    | '/about'
    | '/chapters'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/chapters'
    | '/admin/events'
    | '/admin/media'
    | '/admin/news'
    | '/admin/outreaches'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/doctors-arm'
    | '/events'
    | '/give'
    | '/global-network'
    | '/impact'
    | '/media-resources'
    | '/membership'
    | '/ministries'
    | '/publications'
    | '/students-arm'
    | '/studio'
    | '/what-we-do'
    | '/about/history'
    | '/about/leadership'
    | '/admin/_layout'
    | '/admin/login'
    | '/chapters/$slug'
    | '/global-network/$slug'
    | '/ministries/excel'
    | '/ministries/ifehl'
    | '/ministries/imm'
    | '/ministries/saline-training'
    | '/ministries/the-lady-doctor'
    | '/ministries/wholeness-missions'
    | '/zones/$slug'
    | '/about/'
    | '/chapters/'
    | '/admin/_layout/announcements'
    | '/admin/_layout/audit'
    | '/admin/_layout/chapters'
    | '/admin/_layout/events'
    | '/admin/_layout/media'
    | '/admin/_layout/news'
    | '/admin/_layout/outreaches'
    | '/admin/_layout/pages'
    | '/admin/_layout/settings'
    | '/admin/_layout/users'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DoctorsArmRoute: typeof DoctorsArmRoute
  EventsRoute: typeof EventsRoute
  GiveRoute: typeof GiveRoute
  GlobalNetworkRoute: typeof GlobalNetworkRouteWithChildren
  ImpactRoute: typeof ImpactRoute
  MediaResourcesRoute: typeof MediaResourcesRoute
  MembershipRoute: typeof MembershipRoute
  MinistriesRoute: typeof MinistriesRouteWithChildren
  PublicationsRoute: typeof PublicationsRoute
  StudentsArmRoute: typeof StudentsArmRoute
  StudioRoute: typeof StudioRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  ZonesSlugRoute: typeof ZonesSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors-arm': {
      id: '/doctors-arm'
      path: '/doctors-arm'
      fullPath: '/doctors-arm'
      preLoaderRoute: typeof DoctorsArmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-network': {
      id: '/global-network'
      path: '/global-network'
      fullPath: '/global-network'
      preLoaderRoute: typeof GlobalNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-resources': {
      id: '/media-resources'
      path: '/media-resources'
      fullPath: '/media-resources'
      preLoaderRoute: typeof MediaResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students-arm': {
      id: '/students-arm'
      path: '/students-arm'
      fullPath: '/students-arm'
      preLoaderRoute: typeof StudentsArmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/about/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-network/$slug': {
      id: '/global-network/$slug'
      path: '/$slug'
      fullPath: '/global-network/$slug'
      preLoaderRoute: typeof GlobalNetworkSlugRouteImport
      parentRoute: typeof GlobalNetworkRoute
    }
    '/ministries/excel': {
      id: '/ministries/excel'
      path: '/excel'
      fullPath: '/ministries/excel'
      preLoaderRoute: typeof MinistriesExcelRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/ifehl': {
      id: '/ministries/ifehl'
      path: '/ifehl'
      fullPath: '/ministries/ifehl'
      preLoaderRoute: typeof MinistriesIfehlRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/imm': {
      id: '/ministries/imm'
      path: '/imm'
      fullPath: '/ministries/imm'
      preLoaderRoute: typeof MinistriesImmRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/saline-training': {
      id: '/ministries/saline-training'
      path: '/saline-training'
      fullPath: '/ministries/saline-training'
      preLoaderRoute: typeof MinistriesSalineTrainingRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/the-lady-doctor': {
      id: '/ministries/the-lady-doctor'
      path: '/the-lady-doctor'
      fullPath: '/ministries/the-lady-doctor'
      preLoaderRoute: typeof MinistriesTheLadyDoctorRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/wholeness-missions': {
      id: '/ministries/wholeness-missions'
      path: '/wholeness-missions'
      fullPath: '/ministries/wholeness-missions'
      preLoaderRoute: typeof MinistriesWholenessMissionsRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/zones/$slug': {
      id: '/zones/$slug'
      path: '/zones/$slug'
      fullPath: '/zones/$slug'
      preLoaderRoute: typeof ZonesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/announcements': {
      id: '/admin/_layout/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminLayoutAnnouncementsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/audit': {
      id: '/admin/_layout/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminLayoutAuditRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/chapters': {
      id: '/admin/_layout/chapters'
      path: '/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AdminLayoutChaptersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/events': {
      id: '/admin/_layout/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminLayoutEventsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/media': {
      id: '/admin/_layout/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminLayoutMediaRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/news': {
      id: '/admin/_layout/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminLayoutNewsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/outreaches': {
      id: '/admin/_layout/outreaches'
      path: '/outreaches'
      fullPath: '/admin/outreaches'
      preLoaderRoute: typeof AdminLayoutOutreachesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pages': {
      id: '/admin/_layout/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminLayoutPagesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface GlobalNetworkRouteChildren {
  GlobalNetworkSlugRoute: typeof GlobalNetworkSlugRoute
}

const GlobalNetworkRouteChildren: GlobalNetworkRouteChildren = {
  GlobalNetworkSlugRoute: GlobalNetworkSlugRoute,
}

const GlobalNetworkRouteWithChildren = GlobalNetworkRoute._addFileChildren(
  GlobalNetworkRouteChildren,
)

interface MinistriesRouteChildren {
  MinistriesExcelRoute: typeof MinistriesExcelRoute
  MinistriesIfehlRoute: typeof MinistriesIfehlRoute
  MinistriesImmRoute: typeof MinistriesImmRoute
  MinistriesSalineTrainingRoute: typeof MinistriesSalineTrainingRoute
  MinistriesTheLadyDoctorRoute: typeof MinistriesTheLadyDoctorRoute
  MinistriesWholenessMissionsRoute: typeof MinistriesWholenessMissionsRoute
}

const MinistriesRouteChildren: MinistriesRouteChildren = {
  MinistriesExcelRoute: MinistriesExcelRoute,
  MinistriesIfehlRoute: MinistriesIfehlRoute,
  MinistriesImmRoute: MinistriesImmRoute,
  MinistriesSalineTrainingRoute: MinistriesSalineTrainingRoute,
  MinistriesTheLadyDoctorRoute: MinistriesTheLadyDoctorRoute,
  MinistriesWholenessMissionsRoute: MinistriesWholenessMissionsRoute,
}

const MinistriesRouteWithChildren = MinistriesRoute._addFileChildren(
  MinistriesRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminLayoutAnnouncementsRoute: typeof AdminLayoutAnnouncementsRoute
  AdminLayoutAuditRoute: typeof AdminLayoutAuditRoute
  AdminLayoutChaptersRoute: typeof AdminLayoutChaptersRoute
  AdminLayoutEventsRoute: typeof AdminLayoutEventsRoute
  AdminLayoutMediaRoute: typeof AdminLayoutMediaRoute
  AdminLayoutNewsRoute: typeof AdminLayoutNewsRoute
  AdminLayoutOutreachesRoute: typeof AdminLayoutOutreachesRoute
  AdminLayoutPagesRoute: typeof AdminLayoutPagesRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAnnouncementsRoute: AdminLayoutAnnouncementsRoute,
  AdminLayoutAuditRoute: AdminLayoutAuditRoute,
  AdminLayoutChaptersRoute: AdminLayoutChaptersRoute,
  AdminLayoutEventsRoute: AdminLayoutEventsRoute,
  AdminLayoutMediaRoute: AdminLayoutMediaRoute,
  AdminLayoutNewsRoute: AdminLayoutNewsRoute,
  AdminLayoutOutreachesRoute: AdminLayoutOutreachesRoute,
  AdminLayoutPagesRoute: AdminLayoutPagesRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DoctorsArmRoute: DoctorsArmRoute,
  EventsRoute: EventsRoute,
  GiveRoute: GiveRoute,
  GlobalNetworkRoute: GlobalNetworkRouteWithChildren,
  ImpactRoute: ImpactRoute,
  MediaResourcesRoute: MediaResourcesRoute,
  MembershipRoute: MembershipRoute,
  MinistriesRoute: MinistriesRouteWithChildren,
  PublicationsRoute: PublicationsRoute,
  StudentsArmRoute: StudentsArmRoute,
  StudioRoute: StudioRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  ZonesSlugRoute: ZonesSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
