export const PERMISSION_KEYS = [
  "users.read",
  "users.write",
  "users.delete",
  "users.assign_roles",
  "chapters.read",
  "chapters.write",
  "chapters.delete",
  "leaders.read",
  "leaders.write",
  "leaders.delete",
  "events.read",
  "events.write",
  "events.delete",
  "news.read",
  "news.write",
  "news.delete",
  "announcements.read",
  "announcements.write",
  "announcements.delete",
  "outreaches.read",
  "outreaches.write",
  "outreaches.delete",
  "statistics.read",
  "statistics.write",
  "media.read",
  "media.write",
  "media.delete",
  "pages.read",
  "pages.write",
  "pages.delete",
  "settings.read",
  "settings.write",
  "audit_logs.view",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export const PERMISSION_DESCRIPTIONS: Record<PermissionKey, string> = {
  "users.read": "View users within the allowed scope.",
  "users.write": "Create or update users within the allowed scope.",
  "users.delete": "Deactivate or remove users within the allowed scope.",
  "users.assign_roles": "Assign and revoke roles within the allowed scope.",
  "chapters.read": "View chapters.",
  "chapters.write": "Create or update chapters.",
  "chapters.delete": "Delete chapters.",
  "leaders.read": "View leadership records.",
  "leaders.write": "Create or update leadership records.",
  "leaders.delete": "Delete leadership records.",
  "events.read": "View events.",
  "events.write": "Create or update events.",
  "events.delete": "Delete events.",
  "news.read": "View news posts.",
  "news.write": "Create or update news posts.",
  "news.delete": "Delete news posts.",
  "announcements.read": "View announcements.",
  "announcements.write": "Create or update announcements.",
  "announcements.delete": "Delete announcements.",
  "outreaches.read": "View outreach campaigns.",
  "outreaches.write": "Create or update outreach campaigns.",
  "outreaches.delete": "Delete outreach campaigns.",
  "statistics.read": "View aggregate statistics.",
  "statistics.write": "Update aggregate statistics.",
  "media.read": "View media library assets.",
  "media.write": "Upload or update media assets.",
  "media.delete": "Delete media assets.",
  "pages.read": "View public page content.",
  "pages.write": "Edit public page content.",
  "pages.delete": "Delete public page content.",
  "settings.read": "View site settings.",
  "settings.write": "Update site settings.",
  "audit_logs.view": "View audit logs.",
};

export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSION_KEYS as readonly string[]).includes(value);
}
